# Generated by Django 4.0.6 on 2022-07-23 09:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('direction', '0002_alter_direction_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Оплата')),
                ('company', models.CharField(blank=True, max_length=100, null=True, verbose_name='Компания(не обязательно)')),
                ('contract', models.BooleanField(choices=[(True, 'Договорная'), (False, 'Не договорная')], verbose_name='Цена')),
                ('direction', models.ManyToManyField(blank=True, null=True, to='direction.direction')),
            ],
        ),
    ]
