# Generated by Django 4.0.6 on 2022-07-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direction', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Заказчик', 'verbose_name_plural': 'Заказчики'},
        ),
        migrations.AlterModelOptions(
            name='developer',
            options={'verbose_name': 'Разработчик', 'verbose_name_plural': 'Разработчики'},
        ),
        migrations.AlterField(
            model_name='developer',
            name='direction',
            field=models.ManyToManyField(blank=True, null=True, to='direction.direction'),
        ),
        migrations.DeleteModel(
            name='Direction',
        ),
    ]
