# Generated by Django 4.0.6 on 2022-07-23 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direction', '0001_initial'),
        ('user', '0002_alter_customer_options_alter_developer_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='direction',
            field=models.ManyToManyField(blank=True, null=True, to='direction.direction'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Developer',
        ),
    ]
